version: "3"

services:
  db:
    container_name: db
    image: mysql
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: library
    volumes:
      - ./.data:/var/lib/mysql
      - ./migrations:/migrations